"""PDF export utility using ReportLab."""
from __future__ import annotations
import os
import re
from pathlib import Path
from datetime import datetime


def export_to_pdf(report_markdown: str, title: str) -> str:
    """Convert a markdown report to PDF. Returns the file path."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, ListFlowable, ListItem
    )

    exports_dir = Path(__file__).parent.parent.parent / "exports"
    exports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = re.sub(r'[^\w\s-]', '', title)[:40].strip().replace(' ', '_')
    filename = exports_dir / f"{safe_title}_{timestamp}.pdf"

    doc = SimpleDocTemplate(
        str(filename),
        pagesize=A4,
        rightMargin=2.5 * cm,
        leftMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='ReportTitle',
        parent=styles['Title'],
        fontSize=22,
        spaceAfter=20,
        textColor=colors.HexColor('#1a1a2e'),
    ))
    styles.add(ParagraphStyle(
        name='H1',
        parent=styles['Heading1'],
        fontSize=16,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor('#16213e'),
    ))
    styles.add(ParagraphStyle(
        name='H2',
        parent=styles['Heading2'],
        fontSize=13,
        spaceBefore=12,
        spaceAfter=6,
        textColor=colors.HexColor('#0f3460'),
    ))
    styles.add(ParagraphStyle(
        name='BodyText2',
        parent=styles['BodyText'],
        fontSize=10,
        leading=16,
        spaceAfter=6,
    ))

    story = []
    story.append(Paragraph(title, styles['ReportTitle']))
    story.append(Paragraph(
        f"Generated by Research Intelligence Engine · {datetime.now().strftime('%B %d, %Y')}",
        styles['Italic']
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0'), spaceAfter=16))
    story.append(Spacer(1, 12))

    # Strip out mermaid diagrams since ReportLab cannot render them visually
    clean_report = re.sub(r'```mermaid.*?```', '', report_markdown, flags=re.DOTALL)

    # Parse markdown into ReportLab elements
    lines = clean_report.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
            continue

        # Clean markdown syntax for ReportLab
        clean = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
        clean = re.sub(r'\*(.*?)\*', r'<i>\1</i>', clean)
        clean = re.sub(r'`(.*?)`', r'<font name="Courier">\1</font>', clean)
        clean = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', clean)  # Strip markdown links

        if line.startswith('# '):
            story.append(Spacer(1, 8))
            story.append(Paragraph(line[2:], styles['H1']))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cccccc'), spaceAfter=8))
        elif line.startswith('## '):
            story.append(Paragraph(line[3:], styles['H1']))
        elif line.startswith('### '):
            story.append(Paragraph(line[4:], styles['H2']))
        elif line.startswith('- ') or line.startswith('* '):
            story.append(Paragraph(f"• {clean[2:]}", styles['BodyText2']))
        elif line.startswith('---'):
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#eeeeee'), spaceAfter=8))
        else:
            try:
                story.append(Paragraph(clean, styles['BodyText2']))
            except Exception:
                story.append(Paragraph(line, styles['BodyText2']))

    doc.build(story)
    return str(filename)
